#spring.application.name=API-GATEWAY
#
#server.port=9191
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#
## Order Service
#spring.cloud.gateway.server.webflux.routes[0].id=ORDER-SERVICE
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/order/**
#
## Payment Service
#spring.cloud.gateway.server.webflux.routes[1].id=PAYMENT-SERVICE
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://PAYMENT-SERVICE
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payment/**
#
#management.endpoints.web.exposure.include=*



spring.application.name=API-GATEWAY

server.port=9191

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Order Service
spring.cloud.gateway.server.webflux.routes[0].id=ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/order/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=order-service
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/orderFallback

# Payment Service
spring.cloud.gateway.server.webflux.routes[1].id=PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/payment/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=payment-service
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/paymentFallback

management.endpoints.web.exposure.include=*


resilience4j.timelimiter.instances.order-service.timeout-duration=5s
resilience4j.timelimiter.instances.payment-service.timeout-duration=5s